# Generated by Django 3.2.25 on 2024-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20241122_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='grade_remark',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('pending', 'pending')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade_type',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
