# Generated by Django 3.2.25 on 2024-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20241127_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
